# Generated by Django 5.2 on 2026-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="body_part",
            field=models.CharField(
                choices=[
                    ("chest", "Chest"),
                    ("back", "Back"),
                    ("shoulders", "Shoulders"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("legs", "Legs"),
                    ("core", "Core"),
                    ("cardio", "Cardio"),
                ],
                default="chest",
                max_length=20,
            ),
        ),
    ]
